[package]
name = "db-cmp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
byodb-rust = { git = "https://github.com/five-vee/byodb-rust", version = "0.1.0" }
rand = "0.9.1"
rand_chacha = "0.9.0"
tempfile = "3.20.0"
